### ISSUE TITLE
Could you maybe further expand on how to go about using this script?

### ISSUE THREAD

**Issue by claudeLovelace** [LIJI32/ttcpad#2]
I'm trying to port some fonts into WDBFontOverwrite but I'm not exactly sure how I should use ttcpad. I already installed what I need for Objective-C for Windows but I still don't know what to do next. Could you provide some guidance?

Thanks!

**Comment by LIJI32** [comment]
This utility has not been tested outside of macOS and I'm not sure how compilation of Objective-C utilities on Windows would work. In any case, I'm fairly certain newer versions of `WDBFontOverwrite` have been updated so they can overwrite the last byte of a page as well, making this utility no longer required.
